name = "getfitai"
compatibility_date = "2026-05-31"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "getfitai-db"
database_id = "1b953c77-2f09-46d9-8acb-40b313a9f47c"

# KV 存储
[[kv_namespaces]]
binding = "KV"
id = "74314b60f1064470b52689b83dfec3b8"

# 环境变量
[vars]
NEXT_PUBLIC_APP_URL = "https://www.getfitai.io"
