import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | GetFitAI",
  description: "Read the terms of service for GetFitAI. By using our AI workout generator and fitness calculators, you agree to these conditions.",
  alternates: {
    canonical: "https://www.getfitai.io/terms/",
  },
  openGraph: {
    url: "https://www.getfitai.io/terms",
    images: [
      {
        url: "https://www.getfitai.io/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "GetFitAI - Free AI Workout Generator & Fitness Tools",
      },
    ],
  },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background">
<section className="pt-32 pb-16 px-4 sm:px-6">
        <div className="max-w-3xl mx-auto">
          <div className="mb-12">
            <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-4">
              Terms of Service
            </h1>
            <p className="text-muted-foreground">Last updated: May 20, 2025</p>
          </div>

          <div className="prose prose-neutral max-w-none">
            <h2 className="text-xl font-bold text-foreground mt-8 mb-4">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground mb-6">
              By accessing or using GetFitAI, you agree to be bound by these Terms of Service. 
              If you do not agree, please do not use our services.
            </p>

            <h2 className="text-xl font-bold text-foreground mt-8 mb-4">2. Medical Disclaimer</h2>
            <p className="text-muted-foreground mb-6">
              GetFitAI provides general fitness information and AI-generated workout plans. 
              These are not medical advice. Consult a healthcare professional before starting 
              any exercise program, especially if you have pre-existing conditions or injuries.
            </p>

            <h2 className="text-xl font-bold text-foreground mt-8 mb-4">3. Use of Service</h2>
            <p className="text-muted-foreground mb-4">You agree to:</p>
            <ul className="list-disc list-inside text-muted-foreground mb-6 space-y-2">
              <li>Use the service for personal, non-commercial purposes</li>
              <li>Not abuse or attempt to overload our systems</li>
              <li>Not use the service for any illegal purpose</li>
            </ul>

            <h2 className="text-xl font-bold text-foreground mt-8 mb-4">4. AI-Generated Content</h2>
            <p className="text-muted-foreground mb-6">
              Workout plans are generated by AI and should be reviewed for safety and suitability. 
              We make no guarantees about results. Always exercise within your abilities and 
              stop if you experience pain or discomfort.
            </p>

            <h2 className="text-xl font-bold text-foreground mt-8 mb-4">5. Limitation of Liability</h2>
            <p className="text-muted-foreground mb-6">
              GetFitAI is not liable for any injuries, damages, or losses resulting from use of 
              our service or following our workout recommendations. You assume all risks associated 
              with physical exercise.
            </p>

            <h2 className="text-xl font-bold text-foreground mt-8 mb-4">6. Changes to Terms</h2>
            <p className="text-muted-foreground mb-6">
              We may update these terms at any time. Continued use after changes constitutes 
              acceptance of the new terms.
            </p>

            <h2 className="text-xl font-bold text-foreground mt-8 mb-4">7. Contact</h2>
            <p className="text-muted-foreground mb-6">
              For questions about these terms, contact us at{" "}
              <a href="/contact" className="text-orange-400 hover:underline">
                our contact page
              </a>
              .
            </p>
          </div>
        </div>
      </section>
</main>
  );
}
